model:
  base_learning_rate: 1.0e-06
  palette_params:
    beta_schedule:
      train:
        schedule: linear
        num_timesteps: 2000
        linear_start: 1.0e-06
        linear_end: 0.01
      test:
        schedule: linear
        num_timesteps: 1000
        linear_start: 1.0e-04
        linear_end: 0.09
  unet_params:
    image_size: 64
    in_channels: 3
    out_channels: 3
    model_channels: 64
    dims: 2
    attention_resolutions:
    - 8
    - 4
    - 2
    num_res_blocks: 2
    channel_mult:
    - 1
    - 2
    - 3
    - 5
    num_heads: 1
    use_spatial_transformer: false
data:
  target: main.DataModuleFromConfig
  params:
    num_workers: 1
    batch_size: 3
    wrap: True
    train:
      target: ldm.data.nmr_sharded.NMRShardedDataset
      params:
        start_shard: 0
        end_shard: 0
        path: /scratch/work/spieglb1/datasets/NMR_sharded
        mode: train

    test:
      target: ldm.data.nmr_sharded.NMRShardedDataset
      params:
        start_shard: 0
        end_shard: 0
        path: /scratch/work/spieglb1/datasets/NMR_sharded
        mode: test

    validation:
      target: ldm.data.nmr_sharded.NMRShardedDataset
      params:
        start_shard: 0
        end_shard: 0
        path: /scratch/work/spieglb1/datasets/NMR_sharded
        mode: val